### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ricleal** [neutrons/sns-plot-fit#1]
Let's keep the todo list here. Check when done.

- [x] Add error bars: `sqrt(y)`
- [x] Quick plot:
	- [x] Add metadata to the bottom of the plot (same style as the main plot)
	- [x] Add New Tag or select from existing ones. Sort of dropdown with checkbox. Example: https://codepen.io/eredacokmerke/pen/LEpNLg
- [x] Filter the data by the tags:
	- [x] On the file explorer use the tags previously created as the SANS group principle.
- [x] Correct Fitting equations with the right guess values. See:
	- [x] Gaussian: https://github.com/ricleal/PythonCode/blob/master/Fitting/gaussian_guess.py
	- [x] Lorentzian: https://github.com/ricleal/PythonCode/blob/master/Fitting/lorentz_guess.py
- [x] Fitting: Merge Coefficients input fields and initial values fields so we have a single set of fields.
- [x] Fix Coefficientes: Add a checkbox to the input fields and pass them as constants to the fit engine
- [x] Multiple Fittings:
	- [x] Add a `+` to the equation to sum another equation to the existing one.
	- [x] The next equation coefficients should have concatenated an index and probably should be in parenteses.
		- E.g.: `(m*x+b)+(m1*x+b1)+(m2*x+b2)`
    - [x] Add a Background option. This should be a `-` and a equation to subratct rather them sum.
- [ ] Pass `url` and `filename` parameter in the URL: `?url=/asaas/asasas/&filename=file.dat`.
  - If the `url` is present, fetch the address and populate the explorer tab.
  - If both the `url` and `filename` are present, the explorer tab is populated and the `filename` will be plotted.
  - The `Fetch` button should look in the same URL for new content and update the explorer.
- [ ] Replace `bootstrap` with [vuetify](https://vuetifyjs.com/)
- [ ] Save Dashboard Status
	- This one needs some time... very low priority...
